
server:
  port: 8081
spring:
  application:
    name: gipher-manager
  data:
    mongodb:
      host: nikitha_mongo
  kafka:
    bootstrap-address: kafka:9093

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka